import type { Metadata } from "next";
import { PageHero, SiteFooter, SiteHeader } from "../components/SiteChrome";

export const metadata: Metadata = { title: "Informativa privacy", description: "Informativa sul trattamento dei dati personali ai sensi del Regolamento UE 2016/679." };

export default function Privacy() { return <><SiteHeader/><main><PageHero eyebrow="Trasparenza e dati personali" title="Informativa privacy" text="Informativa resa ai sensi dell’art. 13 del Regolamento UE 2016/679 (GDPR). Ultimo aggiornamento: 10 agosto 2026."/><article className="legal-page content-section">
  <section><h2>1. Titolare del trattamento</h2><p>Il Titolare è <strong>COSTRUZIONI EDILI SHIBA DI SHIBA ERMAL &amp; C. S.A.S.</strong>, con sede in Via Giacomo Brodolini 14, 56017 San Giuliano Terme (PI), P. IVA e Codice Fiscale 02226750509, in persona del legale rappresentante Ermal Shiba.</p><p>Contatti: <a href="mailto:info@shibacostruzioni.it">info@shibacostruzioni.it</a> - PEC: <a href="mailto:ershiba@pec.it">ershiba@pec.it</a>.</p></section>
  <section><h2>2. Dati trattati e finalità</h2><p>Attraverso il modulo di contatto trattiamo nome e cognome, indirizzo e-mail, eventuale numero di telefono, servizio richiesto e contenuto del messaggio. I dati sono usati esclusivamente per ricevere la richiesta, rispondere, organizzare un sopralluogo e predisporre un eventuale preventivo.</p><p>Non inserire nel messaggio dati sanitari, credenziali, documenti, coordinate bancarie o altre informazioni particolarmente riservate.</p></section>
  <section><h2>3. Base giuridica e conferimento</h2><p>La base giuridica è l’esecuzione di misure precontrattuali adottate su richiesta dell’interessato, ai sensi dell’art. 6, par. 1, lett. b) GDPR. I campi obbligatori sono necessari per poter rispondere. La casella nel modulo attesta la presa visione dell’informativa e non costituisce consenso a comunicazioni promozionali.</p></section>
  <section><h2>4. Modalità, sicurezza e conservazione</h2><p>Il trattamento avviene con strumenti informatici e, quando necessario, manuali, nel rispetto dei principi di liceità, correttezza, trasparenza, minimizzazione e sicurezza. Le richieste sono conservate per il tempo necessario a gestire il contatto e gli eventuali rapporti conseguenti; i dati connessi a obblighi amministrativi, fiscali o contrattuali sono conservati per i termini previsti dalla legge.</p></section>
  <section><h2>5. Destinatari e Web3Forms</h2><p>I dati possono essere conosciuti da personale e collaboratori autorizzati e da fornitori tecnici che operano per l’erogazione del servizio. Il modulo è fornito da Web3Forms: i dati inseriti vengono trasmessi tramite il suo servizio per recapitare la richiesta a Costruzioni Edili Shiba. Consulta anche l’<a href="https://web3forms.com/privacy" target="_blank" rel="noreferrer">informativa privacy di Web3Forms</a> per conoscere modalità, conservazione ed eventuali trasferimenti internazionali gestiti dal fornitore.</p><p>I dati non vengono diffusi. Possono essere comunicati a enti pubblici, consulenti o altri soggetti quando necessario per obblighi di legge o per la gestione del rapporto.</p></section>
  <section><h2>6. Navigazione e cookie</h2><p>Il sito non utilizza cookie analitici, pubblicitari o di profilazione. La chiusura dell’avviso informativo viene ricordata nel browser mediante localStorage, esclusivamente per non riproporlo a ogni pagina. Per i dettagli consulta la <a href="../cookie-policy/">Cookie Policy</a>.</p></section>
  <section><h2>7. Diritti dell’interessato</h2><p>Puoi esercitare i diritti previsti dagli artt. 15-22 GDPR, tra cui accesso, rettifica, cancellazione, limitazione, portabilità, opposizione e revoca del consenso quando il trattamento si basa sul consenso. Puoi inoltre proporre reclamo al Garante per la protezione dei dati personali.</p><p>Per esercitare i diritti scrivi a <a href="mailto:ershiba@pec.it">ershiba@pec.it</a> oppure invia una raccomandata A/R alla sede del Titolare.</p></section>
</article></main><SiteFooter/></> }
