import { PageHero, siteUrl, SiteFooter, SiteHeader } from "../components/SiteChrome";
import { pageMetadata } from "../seo";

export const metadata = pageMetadata("Impresa edile a Pisa: chi siamo", "Conosci Costruzioni Edili Shiba, impresa familiare con oltre dieci anni di esperienza e 12 addetti in Toscana.", "/chi-siamo/");

export default function ChiSiamo() {
  return <><SiteHeader /><main><PageHero eyebrow="Chi siamo" title="Esperienza artigiana. Presenza diretta." text="Un’impresa familiare, una rete di professionisti fidati e un unico obiettivo: realizzare lavori solidi, trasparenti e capaci di durare." backgroundImage={siteUrl("/images/muratore-pisa.jpg")} />
    <section className="content-section two-columns"><div><p className="eyebrow">La nostra storia</p><h2>Costruiamo relazioni prima ancora degli spazi.</h2></div><div className="rich-copy"><p>Shiba Costruzioni nasce a Pisa oltre dieci anni fa dalla passione e dalla tenacia di Vaid Shiba. In seguito, anche il figlio Ermal ha scelto di affiancarlo, contribuendo alla crescita dell’impresa familiare. Con dedizione, trasparenza e costanza, l’azienda ha superato le difficoltà e le incertezze incontrate lungo il percorso, ampliandosi fino a raggiungere l’attuale organico di 12 persone.</p><p>Da oltre dieci anni ci occupiamo di ristrutturazione, impermeabilizzazione e manutenzione strutturale degli edifici in Toscana. Ogni incarico nasce dall’ascolto delle esigenze del cliente e da un sopralluogo svolto direttamente dal titolare. Coordiniamo artigiani e tecnici selezionati nel tempo, scegliendo materiali e lavorazioni adatti all’immobile, al contesto e agli obiettivi del progetto.</p></div></section>
    <section className="values-grid values-flow content-section"><article><span>01</span><h3>Trasparenza</h3><p>Preventivi comprensibili, comunicazione diretta e nessuna sorpresa.</p></article><article><span>02</span><h3>Competenza</h3><p>Soluzioni valutate con attenzione tecnica e conoscenza del territorio.</p></article><article><span>03</span><h3>Cura</h3><p>Rispettiamo la casa, le persone e ogni dettaglio della lavorazione.</p></article><article><span>04</span><h3>Responsabilità</h3><p>Privilegiamo interventi efficaci, durevoli e consapevoli.</p></article></section>
  </main><SiteFooter /></>;
}
